# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: 'pipelines-javascript-docker'
  - group : 'aquacredentials'
  - name : aquausername
    value : $[variables.aquausername]
  - name : aquapassword
    value : $[variables.aquapassword]

steps:
- task: Docker@2
  inputs:
    command: 'build'
    Dockerfile: '**/Dockerfile'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      docker login registry.aquasec.com -u $aquausername -p $aquapassword
      docker pull registry.aquasec.com/scanner:6.3
- task: aquasecScanner@4
  inputs:
    image: 'pipelines-javascript-docker'
    scanType: 'local'
    register: false
    hideBase: false
    showNegligible: false
    windowsScannerVersion: '6.5.0'
    scanner: 'registry.aquasec.com/scanner:6.3'
    connection: 'aqua_server_connection'
